### ISSUE TITLE
Better module integration

### ISSUE THREAD

**Issue by matthieuwerner** [matthieuwerner/tf-starter#10]
Module integration could be improve with modules and submodules. 

For now we have just subfolders of "terraform" with contents as self managed projects. It can be painful to reuse that kind code in other architectures.

**Todo :**
- [ ] Split content by service
- [ ] Use terraform/examples/* subfolders to suggest integrations as samples, based on modules created elsewhere (in terraform/modules for example).
- [ ] Update the documentation
