### ISSUE TITLE
Add Databse integration

### ISSUE THREAD

**Issue by matthieuwerner** [matthieuwerner/tf-starter#13]
Add a database integration with RDS, and local containers for local stack.

**Todo:**
- [ ] Add RDS integration
- [ ] Add local mysql integration
- [ ] Add local postgres integration
- [ ] Update the documentation
