### ISSUE TITLE
Add Cloudwatch custom dashboard examples

### ISSUE THREAD

**Issue by matthieuwerner** [matthieuwerner/tf-starter#14]
Add custom dashboards examples with Cloudwatch

**Todo:**
- [ ] Add dashboard integration
- [ ] Create some samples
- [ ] Update the documentation
