### ISSUE TITLE
Improve ES section

### ISSUE THREAD

**Issue by matthieuwerner** [matthieuwerner/tf-starter#3]
Improve ES section by adding more tests on this integration and proposing 2 kinds of installation: aws style, and official with ec2.

**Todo :**

- [ ] Improve ES documentation section
- [ ] Double check aws integration of elastic search terraform
- [ ] Add an official version of elastic search in an EC2 instance
